### ISSUE TITLE
Implement table panels

### ISSUE THREAD

**Issue by matt-daneshvar** [chartello/chartello#3]
As a user I want to be able to see a summary of my data in simple tables.

Example usages:

- Viewing 5 latest users
- Viewing 5 latest subscriptions
- Most active users

Example query:
```
SELECT id, email, created_at
FROM users
WHERE created_at BETWEEN @start AND @end
ORDER BY created_at DESC
```

### Mockup
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/10030505/219538038-ff6f8ead-0b92-4519-93e2-ae3a72437b66.png">

### Todo
- [x] Implement the Vue component
- [x] Create an aggregator for table panels
- [x] Update `Panel.vue` to load its content dynamically
- [x] Add a control for user to change panel type
- [x] Add `type` to panels
- [x] Add help modal
- [x] Ensure `Panel.vue` tolerates incompatible data
- [x] Update the initial dashboard to include a table panel
- [x] Add a section to readme.md
